name: CI

on:
  push:
    tags: '[0-9]+.[0-9]+[0-9]+'
    branches:
      - master
      - workflows
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup APT cache
        uses: actions/cache@v2.1.2
        with:
          path: /var/cache/apt/**
          key: ${{ runner.os }}-apt
      - name: Install Lua and LuaRocks
        run: |
          echo '::group::apt-get update'
          sudo apt-get -q update
          echo '::endGroup::'
          echo '::group::apt-get install'
          sudo apt-get -qy install lua5.1 luarocks liblua5.1-bitop0
          echo '::endGroup::'
          luarocks path --lr-bin >> $GITHUB_PATH
          cat <<EOF >>$GITHUB_ENV
          LUA_PATH=$(luarocks path --lr-path)
          LUA_CPATH=$(luarocks path --lr-cpath)
          EOF
      - name: Setup LuaRocks cache
        id: cache-luarocks
        uses: actions/cache@v2.1.2
        with:
          path: ~/.luarocks
          key: ${{ runner.os }}-luarocks
      - name: Install testing libraries
        if: steps.cache-luarocks.outputs.cache-hit != 'true'
        run: |
          echo '::group::luacheck'
          luarocks install --local luacheck
          echo '::endGroup::'
          echo '::group::mockagne'
          luarocks install --local mockagne 1.0
          echo '::endGroup::'
          echo '::group::luaunit'
          luarocks install --local luaunit 2.1
          echo '::endGroup::'
      - name: Lint
        uses: nebularg/actions-luacheck@v1
      - name: Test
        run: lua tests/Items.lua
      - name: Write libraries to .toc
        run: lua .release/libreplace.lua
      # BigWigsMods/packager only deploy tags
      - name: Package (and deploy)
        uses: BigWigsMods/packager@cd13fb1
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload packages to github
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: .release/AdiButtonAuras*.zip
