name: CI

on:
  push:
    tags: '[0-9]+.[0-9]+[0-9]+'
    branches:
      - master
      - workflows
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Lua and LuaRocks
        run: |
          sudo apt-get -q update
          sudo apt-get -qy install lua5.1 luarocks liblua5.1-bitop0
      - name: Install testing libraries
        run: |
          sudo luarocks install luacheck
          sudo luarocks install mockagne 1.0
          sudo luarocks install luaunit 2.1
      - name: Lint
        uses: nebularg/actions-luacheck@v1
      - name: Test
        run: lua tests/Items.lua
      - name: Write libraries to .toc
        run: lua .release/libreplace.lua
      # BigWigsMods/packager only deploy tags
      - name: Package (and deploy)
        uses: BigWigsMods/packager@cd13fb1
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload packages to github
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: .release/AdiButtonAuras*.zip
