name: CI

on:
  push:
    paths:
      - '**.lua'
      - '.github/workflows/**.yml'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        uses: nebularg/actions-luacheck@v1
        with:
          annotate: warning
          args: --no-color
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.1.5'
      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4
      - name: Install Dependencies
        run: |
          luarocks install luabitop
          luarocks install busted
      - name: Test
        run: |
          cd ./tests
          busted -o TAP .
  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prepare Packager Arguments
        id: packager-args
        if: github.base_ref || github.ref_type != 'tag'
        run: echo "args=-d" >> $GITHUB_OUTPUT
      - name: Package and Release
        uses: BigWigsMods/packager@v2
        with:
          args: ${{ steps.packager-args.outputs.args }}
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
