name: CI

on:
  push:
    tags: '[0-9]+.[0-9]+[0-9]+'
    branches:
      - master
      - workflows
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Lua and LuaRocks
        run: |
          sudo apt-get -q update
          sudo apt-get -qy install lua5.1 luarocks liblua5.1-bitop0
      - name: Install lua rocks
        run: |
          sudo luarocks install luacheck
          sudo luarocks install mockagne 1.0
          sudo luarocks install luaunit 2.1
      - name: Register problem matchers
        run: echo '::add-matcher::.github/luacheck_matcher.json'
      - name: Lint
        run: luacheck . --formatter visual_studio
      - name: Test
        run: lua tests/Items.lua
      - name: Write libraries to .toc
        run: lua .release/libreplace.lua
      # only deploy tags to curse
      - name: Expose the curse forge api key
        if: startsWith(github.ref, 'refs/tags/')
        run: echo '::set-env name=CF_API_KEY::${{ secrets.CF_API_KEY }}'
      - name: Package and deploy
        uses: BigWigsMods/packager@cd13fb1
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}
